### ISSUE TITLE
Steam version

### ISSUE THREAD

**Issue by jdgaravito** [passivestar/substance-tools#4]
Hi I know the steam version is not supported, do you have plans to make it work for that version in the near future?. I would like to have this amazing tool.

**Comment by passivestar** [comment]
Absolutely, the only thing that's stopping me is that I'm on Mac and there's no way for me right now to debug windows-specific code. There's some problem with how arguments are getting passed to substance when launching through steam. But as soon as I find a way I'll be happy to fix that. Shouldn't be hard

**Comment by passivestar** [comment]
Update: just tested on windows with painter 2023 steam edition and it worked perfectly for me. If you have an issue please describe what it is and tell me your OS version and your painter version

**Comment by jdgaravito** [comment]
Hi, I'm on Windows 11 and get the error: Error opening Substance Painter: [WinError 5] Access Denied.

**Comment by Wolfgang-IX** [comment]
> Hi, I'm on Windows 11 and get the error: Error opening Substance Painter: [WinError 5] Access Denied.

it's probably permission issue, try run blender as admin

also i've tested on Windows Blender 3.6.5 & SP 23 Steam version everything works great! thank you @passivestar

**Comment by jdgaravito** [comment]
I did that, run with admin same result, I was thinking the issue was due I'm using blender 4 installed from windows store. I tested with a blender 3.6 portable from blender page and same result. What could it be.

**Comment by jdgaravito** [comment]
I found it, i wasnt view in the path I didn't choose the .EXE, chosed the folder

**Comment by jdgaravito** [comment]
closed

**Comment by passivestar** [comment]
> I found it, i didint specify in the path the .EXE, I chosed the folder mistakenly

@jdgaravito today's version (1.3.14) should also (presumably) autodetect the windows steam painter path automatically
